import pandas as pd
import io

class ReportGenerator:
    """
    Generates downloadable reports for the dashboard.
    """
    @staticmethod
    def generate_csv(df):
        """Returns CSV bytes for the provided dataframe."""
        return df.to_csv(index=False).encode('utf-8')

    @staticmethod
    def generate_pdf_summary(df, fraud_count, high_risk_users, total_tx, f1_score=None):
        """
        Generates a structured text/markdown report that can be saved as PDF or viewed.
        We return bytes that can be handled as a text or simple PDF payload.
        """
        content = [
            "===========================================================",
            "           SURAKSHAPAY ENTERPRISE ANALYTICS REPORT         ",
            "===========================================================",
            f"Total Transactions Analyzed: {total_tx}",
            f"Total Fraud Detected:        {fraud_count}",
            f"Overall Fraud Rate:          {(fraud_count/max(1, total_tx))*100:.2f}%",
            "-----------------------------------------------------------",
            "MODEL PERFORMANCE",
            f"F1 Score (Supervised):       {f1_score if f1_score else 'N/A'}",
            "-----------------------------------------------------------",
            "TOP HIGH RISK USERS (Average Risk Score):",
        ]
        
        for user, score in high_risk_users.items():
            content.append(f" - {user}: {score:.1f}/100")
            
        content.append("===========================================================")
        content.append("Generated by SurakshaPay AI Fraud Engine.")
        
        # Generate a very simple PDF structure natively or just return ASCII text
        text_content = "\n".join(content)
        
        # Since generating real PDFs requires external C libraries or heavy packages (ReportLab, FPDF),
        # we return a UTF-8 encoded text that can be downloaded as a .txt or .md.
        return text_content.encode('utf-8')
